services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: reactive-demo
    ports:
      - '5432:5432'
    volumes:
      - reactive-db-data:/var/lib/postgresql
    networks:
      - app-net
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: mohamecabdelaziz66@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - app-net
    depends_on:
      - postgres

volumes:
  reactive-db-data:
networks:
  app-net: