spring:
  application:
    name: spring-reactive
  r2dbc:
    username: admin
    password: 1234
    url: r2dbc:postgresql://localhost:5432/reactive-demo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/reactive-demo
    user: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
    enabled: false
